name: thepeer_flutter
description: Official plugin for using Thepeer SDK with flutter https://thepeer.co
version: 1.0.6
homepage: https://github.com/thepeerstack/flutter_sdk

environment:
  sdk: '>=2.12.0 <3.0.0'
  

dependencies:
  flutter:
    sdk: flutter

  # UI
  webview_flutter: ^2.0.4
  modal_bottom_sheet: ^2.0.0

  dartz: ^0.10.0-nullsafety.1
  equatable: ^2.0.2

  #hooks_riverpod: ^0.14.0+2
  #flutter_hooks: ^0.16.0

  connectivity: ^3.0.3
  dio: any

  # Others
  logger: ^1.0.0
  pedantic: any

dev_dependencies:
  flutter_test:
    sdk: flutter