name: thepeer_flutter
description: Official plugin for using Thepeer SDK with flutter https://thepeer.co
version: 1.0.4
homepage: https://github.com/thepeerstack/flutter_sdk

environment:
  sdk: '>=2.12.0 <3.0.0'
  

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^2.0.4
  modal_bottom_sheet: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter