name: thepeer_flutter
description: An unofficial plugin for using Peerstack SDK https://thepeer.co/
version: 1.0.1
homepage: https://github.com/zfinix/thepeer_flutter

environment:
  sdk: '>=2.12.0 <3.0.0'
  

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^2.0.4
  modal_bottom_sheet: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter